### ISSUE TITLE
WechatOpenSDK 是不是替换成 WechatOpenSDK-XCFramework？

### ISSUE THREAD

**Issue by openapphub** [niyongsheng/NYSWS#1]
[!] Error installing WechatOpenSDK
[!] /usr/bin/curl -f -L -o /var/folders/l_/5kxy6j356v5d8kmplsbwyvrh0000gn/T/d20241029-24450-88jb56/file.zip https://dldir1.qq.com/WechatWebDev/opensdk/cocoapods/OpenSDK2.0.2.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.15.2 cocoapods-downloader/2.1'

**Comment by niyongsheng** [comment]
`pod cache clean --all`
`pod update`
* 清理下缓存安装、也可以升级下CocoaPods版本
